"""esquema inicial

Revision ID: 098a75fc68d8
Revises: 
Create Date: 2026-09-14 05:49:13.517261
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '098a75fc68d8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('identifier', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('asset_type', sa.Enum('SERVIDOR', 'ESTACAO', 'EQUIPAMENTO_REDE', 'APLICACAO', 'BASE_DADOS', 'SERVICO_CLOUD', 'DISPOSITIVO_MOVEL', 'OUTRO', name='assettype', native_enum=False, length=40), nullable=False),
    sa.Column('criticality', sa.Enum('BAIXA', 'MEDIA', 'ALTA', 'CRITICA', name='assetcriticality', native_enum=False, length=40), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('operating_system', sa.String(length=120), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('business_service', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('wazuh_agent_id', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    sa.UniqueConstraint('identifier', name='uq_assets_identifier')
    )
    op.create_index(op.f('ix_assets_created_at'), 'assets', ['created_at'], unique=False)
    op.create_index(op.f('ix_assets_criticality'), 'assets', ['criticality'], unique=False)
    op.create_index(op.f('ix_assets_hostname'), 'assets', ['hostname'], unique=False)
    op.create_index(op.f('ix_assets_identifier'), 'assets', ['identifier'], unique=False)
    op.create_index(op.f('ix_assets_ip_address'), 'assets', ['ip_address'], unique=False)
    op.create_index('ix_assets_ip_hostname', 'assets', ['ip_address', 'hostname'], unique=False)
    op.create_index(op.f('ix_assets_wazuh_agent_id'), 'assets', ['wazuh_agent_id'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('WAZUH', 'SURICATA', 'QRADAR', 'NETSCOUT', 'MANUAL', 'API_GENERICA', name='sourcekind', native_enum=False, length=40), nullable=False),
    sa.Column('direction', sa.Enum('ENTRADA', 'SAIDA', 'BIDIRECIONAL', name='integrationdirection', native_enum=False, length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NAO_CONFIGURADA', 'CONFIGURADA', 'ACTIVA', 'ERRO', 'DESACTIVADA', name='integrationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secret_env_vars', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_check_ok', sa.Boolean(), nullable=True),
    sa.Column('last_check_detail', sa.Text(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('events_received', sa.BigInteger(), nullable=False),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actions_executed', sa.Integer(), nullable=False),
    sa.Column('actions_failed', sa.Integer(), nullable=False),
    sa.Column('supported_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrations')),
    sa.UniqueConstraint('name', name=op.f('uq_integrations_name'))
    )
    op.create_index(op.f('ix_integrations_created_at'), 'integrations', ['created_at'], unique=False)
    op.create_index(op.f('ix_integrations_kind'), 'integrations', ['kind'], unique=False)
    op.create_index(op.f('ix_integrations_status'), 'integrations', ['status'], unique=False)
    op.create_table('iocs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ioc_type', sa.Enum('IP', 'DOMINIO', 'URL', 'HASH_MD5', 'HASH_SHA1', 'HASH_SHA256', 'EMAIL', 'HOSTNAME', 'UTILIZADOR', 'PROCESSO', 'FICHEIRO', 'CHAVE_REGISTO', 'USER_AGENT', 'CERTIFICADO', name='ioctype', native_enum=False, length=40), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('reputation', sa.Enum('DESCONHECIDA', 'BENIGNA', 'SUSPEITA', 'MALICIOSA', name='iocreputation', native_enum=False, length=40), nullable=False),
    sa.Column('confidence', sa.Enum('BAIXA', 'MEDIA', 'ALTA', 'CONFIRMADA', name='confidence', native_enum=False, length=40), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sighting_count', sa.Integer(), nullable=False),
    sa.Column('is_allowlisted', sa.Boolean(), nullable=False),
    sa.Column('allowlist_reason', sa.Text(), nullable=True),
    sa.Column('enrichment', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_iocs')),
    sa.UniqueConstraint('ioc_type', 'value', name='uq_iocs_type_value')
    )
    op.create_index(op.f('ix_iocs_created_at'), 'iocs', ['created_at'], unique=False)
    op.create_index(op.f('ix_iocs_ioc_type'), 'iocs', ['ioc_type'], unique=False)
    op.create_index(op.f('ix_iocs_is_allowlisted'), 'iocs', ['is_allowlisted'], unique=False)
    op.create_index(op.f('ix_iocs_last_seen'), 'iocs', ['last_seen'], unique=False)
    op.create_index(op.f('ix_iocs_reputation'), 'iocs', ['reputation'], unique=False)
    op.create_index('ix_iocs_reputation_type', 'iocs', ['reputation', 'ioc_type'], unique=False)
    op.create_index(op.f('ix_iocs_risk_score'), 'iocs', ['risk_score'], unique=False)
    op.create_index(op.f('ix_iocs_value'), 'iocs', ['value'], unique=False)
    op.create_table('mitre_tactics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tactic_id', sa.String(length=20), nullable=False),
    sa.Column('shortname', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mitre_tactics'))
    )
    op.create_index(op.f('ix_mitre_tactics_created_at'), 'mitre_tactics', ['created_at'], unique=False)
    op.create_index(op.f('ix_mitre_tactics_ordering'), 'mitre_tactics', ['ordering'], unique=False)
    op.create_index(op.f('ix_mitre_tactics_shortname'), 'mitre_tactics', ['shortname'], unique=False)
    op.create_index(op.f('ix_mitre_tactics_tactic_id'), 'mitre_tactics', ['tactic_id'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_created_at'), 'permissions', ['created_at'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('name', name=op.f('uq_teams_name'))
    )
    op.create_index(op.f('ix_teams_created_at'), 'teams', ['created_at'], unique=False)
    op.create_table('mitre_techniques',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('technique_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('is_subtechnique', sa.Boolean(), nullable=False),
    sa.Column('parent_technique_id', sa.String(length=20), nullable=True),
    sa.Column('tactic_id', sa.UUID(), nullable=True),
    sa.Column('tactic_shortnames', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('platforms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detection', sa.Text(), nullable=False),
    sa.Column('is_deprecated', sa.Boolean(), nullable=False),
    sa.Column('attack_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tactic_id'], ['mitre_tactics.id'], name=op.f('fk_mitre_techniques_tactic_id_mitre_tactics'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mitre_techniques'))
    )
    op.create_index(op.f('ix_mitre_techniques_created_at'), 'mitre_techniques', ['created_at'], unique=False)
    op.create_index(op.f('ix_mitre_techniques_name'), 'mitre_techniques', ['name'], unique=False)
    op.create_index('ix_mitre_techniques_parent', 'mitre_techniques', ['parent_technique_id'], unique=False)
    op.create_index(op.f('ix_mitre_techniques_parent_technique_id'), 'mitre_techniques', ['parent_technique_id'], unique=False)
    op.create_index(op.f('ix_mitre_techniques_technique_id'), 'mitre_techniques', ['technique_id'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_users_team_id_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('integration_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_api_keys_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('fk_api_keys_integration_id_integrations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_api_keys_key_hash')),
    sa.UniqueConstraint('name', name='uq_api_keys_name')
    )
    op.create_index(op.f('ix_api_keys_created_at'), 'api_keys', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'BAIXA', 'MEDIA', 'ALTA', 'CRITICA', name='severity', native_enum=False, length=40), nullable=False),
    sa.Column('confidence', sa.Enum('BAIXA', 'MEDIA', 'ALTA', 'CONFIRMADA', name='confidence', native_enum=False, length=40), nullable=False),
    sa.Column('suspected_actor', sa.String(length=160), nullable=True),
    sa.Column('first_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_engine', sa.Boolean(), nullable=False),
    sa.Column('engine_rationale', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_campaigns_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_index(op.f('ix_campaigns_created_at'), 'campaigns', ['created_at'], unique=False)
    op.create_index(op.f('ix_campaigns_is_active'), 'campaigns', ['is_active'], unique=False)
    op.create_index(op.f('ix_campaigns_reference'), 'campaigns', ['reference'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('INCIDENTE_ATRIBUIDO', 'APROVACAO_PENDENTE', 'ACCAO_EXECUTADA', 'ACCAO_FALHADA', 'TAREFA_ATRIBUIDA', 'INCIDENTE_ESCALADO', 'CORRELACAO_DETECTADA', 'RECOMENDACAO_NOVA', name='notificationkind', native_enum=False, length=40), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'BAIXA', 'MEDIA', 'ALTA', 'CRITICA', name='severity', native_enum=False, length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('resource_reference', sa.String(length=24), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_kind'), 'notifications', ['kind'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_table('playbooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('trigger_category', sa.Enum('CONTEUDO_ABUSIVO', 'CODIGO_MALICIOSO', 'RECOLHA_INFORMACAO', 'TENTATIVA_INTRUSAO', 'INTRUSAO', 'DISPONIBILIDADE', 'SEGURANCA_INFORMACAO', 'FRAUDE', 'VULNERABILIDADE', 'OUTRO', name='incidentcategory', native_enum=False, length=40), nullable=True),
    sa.Column('trigger_min_severity', sa.Enum('INFO', 'BAIXA', 'MEDIA', 'ALTA', 'CRITICA', name='severity', native_enum=False, length=40), nullable=False),
    sa.Column('trigger_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('auto_execute', sa.Boolean(), nullable=False),
    sa.Column('success_criteria', sa.Text(), nullable=False),
    sa.Column('rollback_criteria', sa.Text(), nullable=False),
    sa.Column('closing_status', sa.String(length=40), nullable=True),
    sa.Column('execution_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('last_executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_playbooks_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playbooks')),
    sa.UniqueConstraint('name', name=op.f('uq_playbooks_name'))
    )
    op.create_index(op.f('ix_playbooks_created_at'), 'playbooks', ['created_at'], unique=False)
    op.create_index(op.f('ix_playbooks_is_enabled'), 'playbooks', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_playbooks_trigger_category'), 'playbooks', ['trigger_category'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('TRIAGEM', 'CLASSIFICACAO', 'PRIORIZACAO', 'CORRELACAO', 'TECNICA_MITRE', 'PLAYBOOK', 'FALSO_POSITIVO', 'PROXIMO_PASSO', name='recommendationkind', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'ACEITE', 'REJEITADA', 'EXPIRADA', name='recommendationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('proposed_change', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('engine', sa.String(length=60), nullable=False),
    sa.Column('engine_version', sa.String(length=20), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_id', sa.UUID(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], name=op.f('fk_recommendations_decided_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index(op.f('ix_recommendations_confidence'), 'recommendations', ['confidence'], unique=False)
    op.create_index(op.f('ix_recommendations_created_at'), 'recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_recommendations_kind'), 'recommendations', ['kind'], unique=False)
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    op.create_index('ix_recommendations_status_kind', 'recommendations', ['status', 'kind'], unique=False)
    op.create_index('ix_recommendations_target', 'recommendations', ['target_type', 'target_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=120), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions'))
    )
    op.create_index(op.f('ix_user_sessions_created_at'), 'user_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=True)
    op.create_index('ix_user_sessions_user_active', 'user_sessions', ['user_id', 'revoked_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_email', sa.String(length=254), nullable=False),
    sa.Column('actor_role', sa.String(length=40), nullable=True),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('is_system_actor', sa.Boolean(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('resource_reference', sa.String(length=24), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('origin', sa.String(length=30), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('outcome', sa.Enum('SUCESSO', 'NEGADO', 'FALHA', name='auditoutcome', native_enum=False, length=40), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], name=op.f('fk_audit_logs_api_key_id_api_keys'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_action_time', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_actor_time', 'audit_logs', ['actor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_outcome'), 'audit_logs', ['outcome'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_reference'), 'audit_logs', ['resource_reference'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_table('correlation_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.Enum('ENTIDADE_PARTILHADA', 'SEQUENCIA_TEMPORAL', 'LIMIAR', 'ACTIVO_ALVO', name='correlationstrategy', native_enum=False, length=40), nullable=False),
    sa.Column('window_minutes', sa.Integer(), nullable=False),
    sa.Column('min_alerts', sa.Integer(), nullable=False),
    sa.Column('match_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sequence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resulting_severity', sa.Enum('INFO', 'BAIXA', 'MEDIA', 'ALTA', 'CRITICA', name='severity', native_enum=False, length=40), nullable=True),
    sa.Column('resulting_category', sa.String(length=40), nullable=True),
    sa.Column('incident_title_template', sa.String(length=300), nullable=False),
    sa.Column('suggested_playbook_id', sa.UUID(), nullable=True),
    sa.Column('match_count', sa.Integer(), nullable=False),
    sa.Column('last_matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('false_positive_count', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_correlation_rules_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suggested_playbook_id'], ['playbooks.id'], name=op.f('fk_correlation_rules_suggested_playbook_id_playbooks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_correlation_rules')),
    sa.UniqueConstraint('name', name=op.f('uq_correlation_rules_name'))
    )
    op.create_index(op.f('ix_correlation_rules_created_at'), 'correlation_rules', ['created_at'], unique=False)
    op.create_index(op.f('ix_correlation_rules_is_enabled'), 'correlation_rules', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_correlation_rules_priority'), 'correlation_rules', ['priority'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('CONTEUDO_ABUSIVO', 'CODIGO_MALICIOSO', 'RECOLHA_INFORMACAO', 'TENTATIVA_INTRUSAO', 'INTRUSAO', 'DISPONIBILIDADE', 'SEGURANCA_INFORMACAO', 'FRAUDE', 'VULNERABILIDADE', 'OUTRO', name='incidentcategory', native_enum=False, length=40), nullable=False),
    sa.Column('subtype', sa.String(length=80), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'BAIXA', 'MEDIA', 'ALTA', 'CRITICA', name='severity', native_enum=False, length=40), nullable=False),
    sa.Column('priority', sa.Enum('P4', 'P3', 'P2', 'P1', name='priority', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('NOVO', 'ABERTO', 'TRIAGEM', 'INVESTIGACAO', 'CONTENCAO', 'ERRADICACAO', 'RECUPERACAO', 'RESOLVIDO', 'ENCERRADO', 'SUSPENSO', 'DUPLICADO', 'FALSO_POSITIVO', 'ESCALADO', name='incidentstatus', native_enum=False, length=40), nullable=False),
    sa.Column('confidence', sa.Enum('BAIXA', 'MEDIA', 'ALTA', 'CONFIRMADA', name='confidence', native_enum=False, length=40), nullable=False),
    sa.Column('origin', sa.Enum('REGISTO_MANUAL', 'PROMOCAO_ALERTA', 'CORRELACAO', 'PLAYBOOK', 'ESCALAMENTO', name='incidentorigin', native_enum=False, length=40), nullable=False),
    sa.Column('source_kind', sa.Enum('WAZUH', 'SURICATA', 'QRADAR', 'NETSCOUT', 'MANUAL', 'API_GENERICA', name='sourcekind', native_enum=False, length=40), nullable=False),
    sa.Column('source_detail', sa.String(length=200), nullable=True),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('reporter_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eradicated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('false_positive_reason', sa.Text(), nullable=True),
    sa.Column('affected_users', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_demo_data', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_incidents_assignee_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_incidents_campaign_id_campaigns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_incidents_reporter_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_incidents_team_id_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    op.create_index(op.f('ix_incidents_assignee_id'), 'incidents', ['assignee_id'], unique=False)
    op.create_index('ix_incidents_assignee_status', 'incidents', ['assignee_id', 'status'], unique=False)
    op.create_index(op.f('ix_incidents_campaign_id'), 'incidents', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_incidents_category'), 'incidents', ['category'], unique=False)
    op.create_index(op.f('ix_incidents_created_at'), 'incidents', ['created_at'], unique=False)
    op.create_index(op.f('ix_incidents_detected_at'), 'incidents', ['detected_at'], unique=False)
    op.create_index(op.f('ix_incidents_is_demo_data'), 'incidents', ['is_demo_data'], unique=False)
    op.create_index('ix_incidents_open_priority', 'incidents', ['status', 'priority', 'detected_at'], unique=False)
    op.create_index(op.f('ix_incidents_origin'), 'incidents', ['origin'], unique=False)
    op.create_index(op.f('ix_incidents_priority'), 'incidents', ['priority'], unique=False)
    op.create_index(op.f('ix_incidents_reference'), 'incidents', ['reference'], unique=True)
    op.create_index(op.f('ix_incidents_resolved_at'), 'incidents', ['resolved_at'], unique=False)
    op.create_index(op.f('ix_incidents_risk_score'), 'incidents', ['risk_score'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_source_kind'), 'incidents', ['source_kind'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index('ix_incidents_status_severity', 'incidents', ['status', 'severity'], unique=False)
    op.create_index(op.f('ix_incidents_subtype'), 'incidents', ['subtype'], unique=False)
    op.create_table('playbook_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('playbook_id', sa.UUID(), nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('step_type', sa.Enum('ENRIQUECER_IOC', 'CONSULTAR_REPUTACAO', 'IDENTIFICAR_ACTIVOS', 'CRIAR_TAREFA', 'SOLICITAR_APROVACAO', 'EXECUTAR_ACCAO', 'ALTERAR_ESTADO', 'ATRIBUIR_RESPONSAVEL', 'REGISTAR_NOTA', 'NOTIFICAR', name='playbooksteptype', native_enum=False, length=40), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_kind', sa.Enum('BLOQUEAR_IP', 'DESBLOQUEAR_IP', 'ISOLAR_ACTIVO', 'REMOVER_ISOLAMENTO', 'DESACTIVAR_UTILIZADOR', 'TERMINAR_SESSOES', 'EXECUTAR_VARRIMENTO', 'RECOLHER_ARTEFACTOS', 'NOTIFICAR_EQUIPA', 'ENRIQUECER_IOC', 'REGISTAR_NOTA', name='actionkind', native_enum=False, length=40), nullable=True),
    sa.Column('risk_level', sa.Enum('BAIXO', 'MODERADO', 'CRITICO', name='actionrisklevel', native_enum=False, length=40), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('abort_on_failure', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], name=op.f('fk_playbook_steps_playbook_id_playbooks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playbook_steps')),
    sa.UniqueConstraint('playbook_id', 'ordering', name='uq_playbook_steps_order')
    )
    op.create_index(op.f('ix_playbook_steps_created_at'), 'playbook_steps', ['created_at'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_kind', sa.Enum('WAZUH', 'SURICATA', 'QRADAR', 'NETSCOUT', 'MANUAL', 'API_GENERICA', name='sourcekind', native_enum=False, length=40), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'BAIXA', 'MEDIA', 'ALTA', 'CRITICA', name='severity', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('NOVO', 'EM_TRIAGEM', 'CORRELACIONADO', 'PROMOVIDO', 'DESCARTADO', 'FALSO_POSITIVO', 'DUPLICADO', name='alertstatus', native_enum=False, length=40), nullable=False),
    sa.Column('dedup_key', sa.String(length=64), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('first_event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('triage_score', sa.Integer(), nullable=False),
    sa.Column('triage_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('false_positive_score', sa.Integer(), nullable=False),
    sa.Column('triage_rationale', sa.Text(), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('correlation_outcome', sa.Enum('SEM_CORRELACAO', 'LIGADO_A_INCIDENTE', 'NOVO_INCIDENTE', 'CAMPANHA_PROPOSTA', 'DUPLICADO_SUPRIMIDO', name='correlationoutcome', native_enum=False, length=40), nullable=False),
    sa.Column('correlation_rule_id', sa.UUID(), nullable=True),
    sa.Column('correlation_rationale', sa.Text(), nullable=True),
    sa.Column('correlated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('duplicate_of_id', sa.UUID(), nullable=True),
    sa.Column('triaged_by_id', sa.UUID(), nullable=True),
    sa.Column('triaged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triage_note', sa.Text(), nullable=True),
    sa.Column('is_demo_data', sa.Boolean(), nullable=False),
    sa.Column('rule_id', sa.String(length=60), nullable=True),
    sa.Column('rule_name', sa.String(length=255), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_alerts_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['correlation_rule_id'], ['correlation_rules.id'], name=op.f('fk_alerts_correlation_rule_id_correlation_rules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['alerts.id'], name=op.f('fk_alerts_duplicate_of_id_alerts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_alerts_incident_id_incidents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triaged_by_id'], ['users.id'], name=op.f('fk_alerts_triaged_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_dedup_key'), 'alerts', ['dedup_key'], unique=False)
    op.create_index('ix_alerts_dedup_open', 'alerts', ['dedup_key', 'status'], unique=False)
    op.create_index(op.f('ix_alerts_incident_id'), 'alerts', ['incident_id'], unique=False)
    op.create_index(op.f('ix_alerts_is_demo_data'), 'alerts', ['is_demo_data'], unique=False)
    op.create_index(op.f('ix_alerts_last_event_at'), 'alerts', ['last_event_at'], unique=False)
    op.create_index(op.f('ix_alerts_reference'), 'alerts', ['reference'], unique=True)
    op.create_index(op.f('ix_alerts_rule_id'), 'alerts', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_source_kind'), 'alerts', ['source_kind'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_status_severity', 'alerts', ['status', 'severity'], unique=False)
    op.create_index('ix_alerts_triage_queue', 'alerts', ['status', 'triage_score', 'last_event_at'], unique=False)
    op.create_index(op.f('ix_alerts_triage_score'), 'alerts', ['triage_score'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_comments_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_comments_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.create_index('ix_comments_incident_created', 'comments', ['incident_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_comments_is_system'), 'comments', ['is_system'], unique=False)
    op.create_table('incident_assets',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_incident_assets_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_assets_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id', 'asset_id', name=op.f('pk_incident_assets'))
    )
    op.create_table('incident_relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_incident_id', sa.UUID(), nullable=False),
    sa.Column('target_incident_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.Enum('DUPLICADO_DE', 'RELACIONADO_COM', 'CAUSADO_POR', 'ORIGINOU', 'PARTE_DE_CAMPANHA', 'ESCALADO_DE', name='relationtype', native_enum=False, length=40), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_by_engine', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Enum('BAIXA', 'MEDIA', 'ALTA', 'CONFIRMADA', name='confidence', native_enum=False, length=40), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_incident_relations_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_incident_id'], ['incidents.id'], name=op.f('fk_incident_relations_source_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_incident_id'], ['incidents.id'], name=op.f('fk_incident_relations_target_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_relations')),
    sa.UniqueConstraint('source_incident_id', 'target_incident_id', 'relation_type', name='uq_incident_relations_edge')
    )
    op.create_index(op.f('ix_incident_relations_created_at'), 'incident_relations', ['created_at'], unique=False)
    op.create_index('ix_incident_relations_target', 'incident_relations', ['target_incident_id'], unique=False)
    op.create_table('incident_techniques',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('technique_id', sa.UUID(), nullable=False),
    sa.Column('is_asserted', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Enum('BAIXA', 'MEDIA', 'ALTA', 'CONFIRMADA', name='confidence', native_enum=False, length=40), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_incident_techniques_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_techniques_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technique_id'], ['mitre_techniques.id'], name=op.f('fk_incident_techniques_technique_id_mitre_techniques'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_techniques')),
    sa.UniqueConstraint('incident_id', 'technique_id', name='uq_incident_techniques')
    )
    op.create_index(op.f('ix_incident_techniques_created_at'), 'incident_techniques', ['created_at'], unique=False)
    op.create_index(op.f('ix_incident_techniques_is_asserted'), 'incident_techniques', ['is_asserted'], unique=False)
    op.create_table('playbook_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=24), nullable=False),
    sa.Column('playbook_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'EM_EXECUCAO', 'AGUARDA_APROVACAO', 'CONCLUIDA', 'FALHADA', 'CANCELADA', name='playbookexecutionstatus', native_enum=False, length=40), nullable=False),
    sa.Column('playbook_version', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_by_id', sa.UUID(), nullable=True),
    sa.Column('triggered_automatically', sa.Boolean(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_playbook_executions_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], name=op.f('fk_playbook_executions_playbook_id_playbooks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], name=op.f('fk_playbook_executions_triggered_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playbook_executions'))
    )
    op.create_index(op.f('ix_playbook_executions_created_at'), 'playbook_executions', ['created_at'], unique=False)
    op.create_index('ix_playbook_executions_incident', 'playbook_executions', ['incident_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_playbook_executions_incident_id'), 'playbook_executions', ['incident_id'], unique=False)
    op.create_index(op.f('ix_playbook_executions_reference'), 'playbook_executions', ['reference'], unique=True)
    op.create_index(op.f('ix_playbook_executions_status'), 'playbook_executions', ['status'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=24), nullable=False),
    sa.Column('kind', sa.Enum('INCIDENTE', 'INVESTIGACAO', 'ACTIVIDADE', 'PERIODO', 'SEVERIDADE', 'DESEMPENHO', 'RESPOSTA', name='reportkind', native_enum=False, length=40), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('generated_by_id', sa.UUID(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], name=op.f('fk_reports_generated_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_reports_incident_id_incidents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_kind'), 'reports', ['kind'], unique=False)
    op.create_index('ix_reports_kind_created', 'reports', ['kind', 'created_at'], unique=False)
    op.create_index(op.f('ix_reports_reference'), 'reports', ['reference'], unique=True)
    op.create_table('actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=24), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('action_kind', sa.Enum('BLOQUEAR_IP', 'DESBLOQUEAR_IP', 'ISOLAR_ACTIVO', 'REMOVER_ISOLAMENTO', 'DESACTIVAR_UTILIZADOR', 'TERMINAR_SESSOES', 'EXECUTAR_VARRIMENTO', 'RECOLHER_ARTEFACTOS', 'NOTIFICAR_EQUIPA', 'ENRIQUECER_IOC', 'REGISTAR_NOTA', name='actionkind', native_enum=False, length=40), nullable=False),
    sa.Column('risk_level', sa.Enum('BAIXO', 'MODERADO', 'CRITICO', name='actionrisklevel', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('PROPOSTA', 'AGUARDA_APROVACAO', 'APROVADA', 'REJEITADA', 'EM_EXECUCAO', 'EXECUTADA', 'FALHADA', 'REVERTIDA', 'CANCELADA', name='actionstatus', native_enum=False, length=40), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('target', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('integration_id', sa.UUID(), nullable=True),
    sa.Column('proposed_by_id', sa.UUID(), nullable=True),
    sa.Column('proposed_by_engine', sa.Boolean(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('playbook_execution_id', sa.UUID(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_by_id', sa.UUID(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('is_reversible', sa.Boolean(), nullable=False),
    sa.Column('reverted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reverted_by_action_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['executed_by_id'], ['users.id'], name=op.f('fk_actions_executed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_actions_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('fk_actions_integration_id_integrations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['playbook_execution_id'], ['playbook_executions.id'], name=op.f('fk_actions_playbook_execution_id_playbook_executions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposed_by_id'], ['users.id'], name=op.f('fk_actions_proposed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name=op.f('fk_actions_recommendation_id_recommendations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reverted_by_action_id'], ['actions.id'], name=op.f('fk_actions_reverted_by_action_id_actions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actions'))
    )
    op.create_index(op.f('ix_actions_action_kind'), 'actions', ['action_kind'], unique=False)
    op.create_index(op.f('ix_actions_created_at'), 'actions', ['created_at'], unique=False)
    op.create_index('ix_actions_incident', 'actions', ['incident_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_actions_incident_id'), 'actions', ['incident_id'], unique=False)
    op.create_index(op.f('ix_actions_reference'), 'actions', ['reference'], unique=True)
    op.create_index(op.f('ix_actions_status'), 'actions', ['status'], unique=False)
    op.create_index('ix_actions_status_risk', 'actions', ['status', 'risk_level'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_kind', sa.Enum('WAZUH', 'SURICATA', 'QRADAR', 'NETSCOUT', 'MANUAL', 'API_GENERICA', name='sourcekind', native_enum=False, length=40), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('source_event_id', sa.String(length=200), nullable=False),
    sa.Column('integration_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'BAIXA', 'MEDIA', 'ALTA', 'CRITICA', name='severity', native_enum=False, length=40), nullable=False),
    sa.Column('source_severity', sa.String(length=40), nullable=True),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('destination_ip', sa.String(length=45), nullable=True),
    sa.Column('source_port', sa.Integer(), nullable=True),
    sa.Column('destination_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=20), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=160), nullable=True),
    sa.Column('process', sa.String(length=255), nullable=True),
    sa.Column('file_hash', sa.String(length=128), nullable=True),
    sa.Column('rule_id', sa.String(length=60), nullable=True),
    sa.Column('rule_name', sa.String(length=255), nullable=True),
    sa.Column('rule_groups', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reported_techniques', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_events_alert_id_alerts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_events_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('fk_events_integration_id_integrations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('source_kind', 'source_event_id', name='uq_events_source_eventid')
    )
    op.create_index(op.f('ix_events_alert_id'), 'events', ['alert_id'], unique=False)
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_destination_ip'), 'events', ['destination_ip'], unique=False)
    op.create_index(op.f('ix_events_file_hash'), 'events', ['file_hash'], unique=False)
    op.create_index(op.f('ix_events_host'), 'events', ['host'], unique=False)
    op.create_index(op.f('ix_events_occurred_at'), 'events', ['occurred_at'], unique=False)
    op.create_index('ix_events_occurred_source', 'events', ['occurred_at', 'source_kind'], unique=False)
    op.create_index(op.f('ix_events_rule_id'), 'events', ['rule_id'], unique=False)
    op.create_index(op.f('ix_events_severity'), 'events', ['severity'], unique=False)
    op.create_index(op.f('ix_events_source_ip'), 'events', ['source_ip'], unique=False)
    op.create_index(op.f('ix_events_source_kind'), 'events', ['source_kind'], unique=False)
    op.create_index('ix_events_src_dst', 'events', ['source_ip', 'destination_ip'], unique=False)
    op.create_index(op.f('ix_events_username'), 'events', ['username'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('ioc_id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('ORIGEM', 'DESTINO', 'ALVO', 'PAYLOAD', 'ACTOR', 'ARTEFACTO', 'RELACIONADO', name='observationrole', native_enum=False, length=40), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Enum('BAIXA', 'MEDIA', 'ALTA', 'CONFIRMADA', name='confidence', native_enum=False, length=40), nullable=False),
    sa.Column('is_automatic', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_observations_alert_id_alerts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_observations_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_observations_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_observations_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ioc_id'], ['iocs.id'], name=op.f('fk_observations_ioc_id_iocs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observations')),
    sa.UniqueConstraint('incident_id', 'ioc_id', 'role', 'alert_id', name='uq_observations_sighting')
    )
    op.create_index(op.f('ix_observations_created_at'), 'observations', ['created_at'], unique=False)
    op.create_index('ix_observations_incident', 'observations', ['incident_id', 'role'], unique=False)
    op.create_index(op.f('ix_observations_incident_id'), 'observations', ['incident_id'], unique=False)
    op.create_index(op.f('ix_observations_ioc_id'), 'observations', ['ioc_id'], unique=False)
    op.create_index('ix_observations_ioc_time', 'observations', ['ioc_id', 'observed_at'], unique=False)
    op.create_index(op.f('ix_observations_observed_at'), 'observations', ['observed_at'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'EM_CURSO', 'BLOQUEADA', 'CONCLUIDA', 'CANCELADA', name='taskstatus', native_enum=False, length=40), nullable=False),
    sa.Column('priority', sa.Enum('P4', 'P3', 'P2', 'P1', name='priority', native_enum=False, length=40), nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('playbook_execution_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_tasks_assignee_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_tasks_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_tasks_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playbook_execution_id'], ['playbook_executions.id'], name=op.f('fk_tasks_playbook_execution_id_playbook_executions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index('ix_tasks_assignee_status', 'tasks', ['assignee_id', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_incident_id'), 'tasks', ['incident_id'], unique=False)
    op.create_index('ix_tasks_incident_order', 'tasks', ['incident_id', 'ordering'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('action_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('APROVADA', 'REJEITADA', 'PENDENTE', name='approvaldecision', native_enum=False, length=40), nullable=False),
    sa.Column('required_permission', sa.String(length=64), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_id', sa.UUID(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name=op.f('fk_action_approvals_action_id_actions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], name=op.f('fk_action_approvals_decided_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_approvals'))
    )
    op.create_index(op.f('ix_action_approvals_action_id'), 'action_approvals', ['action_id'], unique=False)
    op.create_index(op.f('ix_action_approvals_created_at'), 'action_approvals', ['created_at'], unique=False)
    op.create_index(op.f('ix_action_approvals_decision'), 'action_approvals', ['decision'], unique=False)
    op.create_index('ix_action_approvals_pending', 'action_approvals', ['decision', 'created_at'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_type', sa.Enum('LOG', 'CAPTURA_ECRA', 'CAPTURA_REDE', 'FICHEIRO', 'RELATORIO', 'ARTEFACTO', 'EVENTO', 'OUTRO', name='evidencetype', native_enum=False, length=40), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=400), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('md5', sa.String(length=32), nullable=True),
    sa.Column('integrity_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('integrity_ok', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=160), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_evidence_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_evidence_task_id_tasks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_evidence_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    op.create_index(op.f('ix_evidence_created_at'), 'evidence', ['created_at'], unique=False)
    op.create_index(op.f('ix_evidence_evidence_type'), 'evidence', ['evidence_type'], unique=False)
    op.create_index('ix_evidence_incident_created', 'evidence', ['incident_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_evidence_incident_id'), 'evidence', ['incident_id'], unique=False)
    op.create_index('ix_evidence_sha256', 'evidence', ['sha256'], unique=False)
    op.create_table('playbook_step_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=200), nullable=False),
    sa.Column('step_type', sa.Enum('ENRIQUECER_IOC', 'CONSULTAR_REPUTACAO', 'IDENTIFICAR_ACTIVOS', 'CRIAR_TAREFA', 'SOLICITAR_APROVACAO', 'EXECUTAR_ACCAO', 'ALTERAR_ESTADO', 'ATRIBUIR_RESPONSAVEL', 'REGISTAR_NOTA', 'NOTIFICAR', name='playbooksteptype', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'EM_CURSO', 'BLOQUEADA', 'CONCLUIDA', 'CANCELADA', name='taskstatus', native_enum=False, length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('action_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name=op.f('fk_playbook_step_executions_action_id_actions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['execution_id'], ['playbook_executions.id'], name=op.f('fk_playbook_step_executions_execution_id_playbook_executions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['playbook_steps.id'], name=op.f('fk_playbook_step_executions_step_id_playbook_steps'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playbook_step_executions'))
    )
    op.create_index(op.f('ix_playbook_step_executions_created_at'), 'playbook_step_executions', ['created_at'], unique=False)
    op.create_index(op.f('ix_playbook_step_executions_execution_id'), 'playbook_step_executions', ['execution_id'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_id'], ['tasks.id'], name=op.f('fk_task_dependencies_depends_on_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_dependencies_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'depends_on_id', name=op.f('pk_task_dependencies'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_dependencies')
    op.drop_index(op.f('ix_playbook_step_executions_execution_id'), table_name='playbook_step_executions')
    op.drop_index(op.f('ix_playbook_step_executions_created_at'), table_name='playbook_step_executions')
    op.drop_table('playbook_step_executions')
    op.drop_index('ix_evidence_sha256', table_name='evidence')
    op.drop_index(op.f('ix_evidence_incident_id'), table_name='evidence')
    op.drop_index('ix_evidence_incident_created', table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_created_at'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_action_approvals_pending', table_name='action_approvals')
    op.drop_index(op.f('ix_action_approvals_decision'), table_name='action_approvals')
    op.drop_index(op.f('ix_action_approvals_created_at'), table_name='action_approvals')
    op.drop_index(op.f('ix_action_approvals_action_id'), table_name='action_approvals')
    op.drop_table('action_approvals')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index('ix_tasks_incident_order', table_name='tasks')
    op.drop_index(op.f('ix_tasks_incident_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_index('ix_tasks_assignee_status', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_observations_observed_at'), table_name='observations')
    op.drop_index('ix_observations_ioc_time', table_name='observations')
    op.drop_index(op.f('ix_observations_ioc_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_incident_id'), table_name='observations')
    op.drop_index('ix_observations_incident', table_name='observations')
    op.drop_index(op.f('ix_observations_created_at'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_events_username'), table_name='events')
    op.drop_index('ix_events_src_dst', table_name='events')
    op.drop_index(op.f('ix_events_source_kind'), table_name='events')
    op.drop_index(op.f('ix_events_source_ip'), table_name='events')
    op.drop_index(op.f('ix_events_severity'), table_name='events')
    op.drop_index(op.f('ix_events_rule_id'), table_name='events')
    op.drop_index('ix_events_occurred_source', table_name='events')
    op.drop_index(op.f('ix_events_occurred_at'), table_name='events')
    op.drop_index(op.f('ix_events_host'), table_name='events')
    op.drop_index(op.f('ix_events_file_hash'), table_name='events')
    op.drop_index(op.f('ix_events_destination_ip'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_index(op.f('ix_events_alert_id'), table_name='events')
    op.drop_table('events')
    op.drop_index('ix_actions_status_risk', table_name='actions')
    op.drop_index(op.f('ix_actions_status'), table_name='actions')
    op.drop_index(op.f('ix_actions_reference'), table_name='actions')
    op.drop_index(op.f('ix_actions_incident_id'), table_name='actions')
    op.drop_index('ix_actions_incident', table_name='actions')
    op.drop_index(op.f('ix_actions_created_at'), table_name='actions')
    op.drop_index(op.f('ix_actions_action_kind'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_reports_reference'), table_name='reports')
    op.drop_index('ix_reports_kind_created', table_name='reports')
    op.drop_index(op.f('ix_reports_kind'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_playbook_executions_status'), table_name='playbook_executions')
    op.drop_index(op.f('ix_playbook_executions_reference'), table_name='playbook_executions')
    op.drop_index(op.f('ix_playbook_executions_incident_id'), table_name='playbook_executions')
    op.drop_index('ix_playbook_executions_incident', table_name='playbook_executions')
    op.drop_index(op.f('ix_playbook_executions_created_at'), table_name='playbook_executions')
    op.drop_table('playbook_executions')
    op.drop_index(op.f('ix_incident_techniques_is_asserted'), table_name='incident_techniques')
    op.drop_index(op.f('ix_incident_techniques_created_at'), table_name='incident_techniques')
    op.drop_table('incident_techniques')
    op.drop_index('ix_incident_relations_target', table_name='incident_relations')
    op.drop_index(op.f('ix_incident_relations_created_at'), table_name='incident_relations')
    op.drop_table('incident_relations')
    op.drop_table('incident_assets')
    op.drop_index(op.f('ix_comments_is_system'), table_name='comments')
    op.drop_index('ix_comments_incident_created', table_name='comments')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_alerts_triage_score'), table_name='alerts')
    op.drop_index('ix_alerts_triage_queue', table_name='alerts')
    op.drop_index('ix_alerts_status_severity', table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_source_kind'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_rule_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_reference'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_last_event_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_demo_data'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_incident_id'), table_name='alerts')
    op.drop_index('ix_alerts_dedup_open', table_name='alerts')
    op.drop_index(op.f('ix_alerts_dedup_key'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_playbook_steps_created_at'), table_name='playbook_steps')
    op.drop_table('playbook_steps')
    op.drop_index(op.f('ix_incidents_subtype'), table_name='incidents')
    op.drop_index('ix_incidents_status_severity', table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_source_kind'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_risk_score'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_resolved_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_reference'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_priority'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_origin'), table_name='incidents')
    op.drop_index('ix_incidents_open_priority', table_name='incidents')
    op.drop_index(op.f('ix_incidents_is_demo_data'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_detected_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_category'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_campaign_id'), table_name='incidents')
    op.drop_index('ix_incidents_assignee_status', table_name='incidents')
    op.drop_index(op.f('ix_incidents_assignee_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_correlation_rules_priority'), table_name='correlation_rules')
    op.drop_index(op.f('ix_correlation_rules_is_enabled'), table_name='correlation_rules')
    op.drop_index(op.f('ix_correlation_rules_created_at'), table_name='correlation_rules')
    op.drop_table('correlation_rules')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_reference'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_outcome'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_time', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_time', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_user_sessions_user_active', table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_created_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_recommendations_target', table_name='recommendations')
    op.drop_index('ix_recommendations_status_kind', table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_kind'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_created_at'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_confidence'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_playbooks_trigger_category'), table_name='playbooks')
    op.drop_index(op.f('ix_playbooks_is_enabled'), table_name='playbooks')
    op.drop_index(op.f('ix_playbooks_created_at'), table_name='playbooks')
    op.drop_table('playbooks')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_kind'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_campaigns_reference'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_is_active'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_created_at'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_created_at'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_mitre_techniques_technique_id'), table_name='mitre_techniques')
    op.drop_index(op.f('ix_mitre_techniques_parent_technique_id'), table_name='mitre_techniques')
    op.drop_index('ix_mitre_techniques_parent', table_name='mitre_techniques')
    op.drop_index(op.f('ix_mitre_techniques_name'), table_name='mitre_techniques')
    op.drop_index(op.f('ix_mitre_techniques_created_at'), table_name='mitre_techniques')
    op.drop_table('mitre_techniques')
    op.drop_index(op.f('ix_teams_created_at'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_created_at'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_mitre_tactics_tactic_id'), table_name='mitre_tactics')
    op.drop_index(op.f('ix_mitre_tactics_shortname'), table_name='mitre_tactics')
    op.drop_index(op.f('ix_mitre_tactics_ordering'), table_name='mitre_tactics')
    op.drop_index(op.f('ix_mitre_tactics_created_at'), table_name='mitre_tactics')
    op.drop_table('mitre_tactics')
    op.drop_index(op.f('ix_iocs_value'), table_name='iocs')
    op.drop_index(op.f('ix_iocs_risk_score'), table_name='iocs')
    op.drop_index('ix_iocs_reputation_type', table_name='iocs')
    op.drop_index(op.f('ix_iocs_reputation'), table_name='iocs')
    op.drop_index(op.f('ix_iocs_last_seen'), table_name='iocs')
    op.drop_index(op.f('ix_iocs_is_allowlisted'), table_name='iocs')
    op.drop_index(op.f('ix_iocs_ioc_type'), table_name='iocs')
    op.drop_index(op.f('ix_iocs_created_at'), table_name='iocs')
    op.drop_table('iocs')
    op.drop_index(op.f('ix_integrations_status'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_kind'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_created_at'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_assets_wazuh_agent_id'), table_name='assets')
    op.drop_index('ix_assets_ip_hostname', table_name='assets')
    op.drop_index(op.f('ix_assets_ip_address'), table_name='assets')
    op.drop_index(op.f('ix_assets_identifier'), table_name='assets')
    op.drop_index(op.f('ix_assets_hostname'), table_name='assets')
    op.drop_index(op.f('ix_assets_criticality'), table_name='assets')
    op.drop_index(op.f('ix_assets_created_at'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
